using System;
using System.Collections.Generic;

namespace Algorithms
{
    public class Fibonacci
    {
        // Each new term in the Fibonacci sequence is generated by adding the previous two terms.By starting with 1 and 2, the first 10 terms will be:
        // 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
        // By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

        public static List<int> GetFibonacciSequence(List<int> list, int maxValue)
        {
            if (list == null || list.Count < 2)
            {
                list = new List<int>()
                {
                    1,2
                };
            }

            var sum = list[list.Count - 1] + list[list.Count - 2];

            if (sum <= maxValue)
            {
                list.Add(sum);
                GetFibonacciSequence(list, maxValue);
            }

            return list;
        }

        public static List<int> GetEvenNumbers(List<int> input)
        {
            var list = new List<int>();
            foreach (var i in input)
            {
                if (i % 2 == 0)
                    list.Add(i);
            }
            return list;
        }
    }
}